name: modul_pratikum_w9_10
description: "A Flutter project for Module W9â€“10 (Persistensi Data & CRUD)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # === Bagian Persistensi Data ===
  shared_preferences: ^2.3.2
  path_provider: ^2.1.3
  sqflite: ^2.3.3
  path: ^1.9.0

  # === ORM (Floor) ===
  floor: ^1.5.0

  # === Networking & API ===
  dio: ^5.4.3
  retrofit: ^4.1.0
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  # === Generator Tools (kompatibel dengan floor_generator) ===
  build_runner: ^2.4.9
  retrofit_generator: ^8.0.6
  json_serializable: ^6.7.0
  floor_generator: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/db/tasks.db
